repos:

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args:
    - doc/

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args:
    - --profile
    - black
    - --force-sort-within-sections
    - --line-length
    - '100'

- repo: https://github.com/PyCQA/flake8
  rev: 7.2.0
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args:
    - --ignore-words=doc/styles/config/vocabularies/ANSYS/accept.txt
    - -S \*.pyc\
    - \*.xml\
    - \*.txt\
    - \*.gif\
    - \*.png\
    - \*.jpg\
    - \*.js\
    - \*.html\
    - \*.doctree\
    - \*.ttf\
    - \*.woff\
    - \*.woff2\
    - \*.eot\
    - \*.mp4\
    - \*.inv\
    - \*.pickle\
    - \*.ipynb\
    - flycheck\*\
    - ./.git/\*\
    - ./.hypothesis/\*\
    - \*.yml\
    - ./doc/build/\*\
    - ./doc/images/\*\
    - ./dist/\*\
    - \*~\
    - .hypothesis\*\
    - ./doc/source/examples/\*\
    - \*cover\
    - \*.dat\
    - \*.mac

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
  - id: check-github-workflows
    name: Check GitHub workflows
    files: ^\.github/workflows/
    types:
    - yaml
