repos:

- repo: https://github.com/psf/black
  rev: 26.5.1
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 9.0.1
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.3
  hooks:
  - id: codespell
    args:
    - --ignore-words
    - doc/styles/config/vocabularies/ANSYS/accept.txt
    - -w

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies:
    - toml
    exclude: tests/

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-merge-conflict
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.38.0
  hooks:
  - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.8.0
  hooks:
  - id: add-license-headers
