# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
    Python311:
      python.version: '3.11'
      tox.env: 'py311'
    Python312:
      python.version: '3.12'
      tox.env: 'py312'
    Python313:
      python.version: '3.13'
      tox.env: 'py313'
    Python314:
      python.version: '3.14'
      tox.env: 'py314'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    python -m pip install pre-commit tox
    tox -e style
  displayName: 'Code Style'

- script: |
    python -m pip install pytest-azurepipelines tox
    tox -e $(tox.env)
  displayName: 'Unit Tests'
