{
 "title": "REP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"}"
    }
   ]
  },
  {
   "title": "Evaluator",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{otelServiceName=\"evaluator\"}"
    }
   ]
  },
  {
   "title": "Legacy Solver",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "{otelServiceName=\"legacy_solver\"}"
    }
   ]
  },
  {
   "title": "Moder Solver",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "{otelServiceName=\"modern_solver\"}"
    }
   ]
  }
 ]
}