name: CI
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.9'
  DOCUMENTATION_CNAME: '.docs.pyansys.com'
  LIBRARY_NAME: 'src'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_HOST_URL: ${{ vars.MEILISEARCH_HOST_URL }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  update-changelog:
    name: "Update CHANGELOG (on release)"
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ansys/actions/doc-deploy-changelog@v6
        with:
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  code-style:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - uses: ansys/actions/code-style@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  doc-style:
    name: "Documentation Style Check"
    runs-on: ubuntu-latest
    steps:
      - name: PyAnsys documentation style checks
        uses: ansys/actions/doc-style@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  smoke-tests:
    name: "Build and Smoke tests"
    runs-on: ${{ matrix.os }}
    needs: [code-style]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: ansys/actions/build-wheelhouse@v6
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

  tests:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    needs: [smoke-tests]
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest]
       python-version: ['3.9', '3.10', '3.11', '3.12']
      fail-fast: false
    steps:
      - name: PyAnsys tests check
        uses: ansys/actions/tests-pytest@v6
        with:
          pytest-extra-args: "--cov=ansys --cov-report=term --cov-report=html:.cov/html"
          python-version: ${{ matrix.python-version }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: env.MAIN_PYTHON_VERSION == matrix.python-version
        with:
          name: coverage-tests-${{ matrix.os }}
          path: .cov
          retention-days: 7

      - name: Upload coverage results (as .coverage)
        uses: actions/upload-artifact@v4
        if: env.MAIN_PYTHON_VERSION == matrix.python-version
        with:
          name: coverage-file-tests-${{ matrix.os }}
          path: .coverage
          retention-days: 7

  doc-build:
    name: "Build documentation"
    runs-on: ubuntu-latest
    needs: [doc-style]
    steps:
      - uses: ansys/actions/doc-build@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  build-library:
    name: "Build library"
    runs-on: ubuntu-latest
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@v6
        with:
          library-name: ${{ env.LIBRARY_NAME }}

  doc-deploy-dev:
    name: "Deploy development documentation"
    runs-on: ubuntu-latest
    needs: [doc-build, build-library]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: ansys/actions/doc-deploy-dev@v6
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  doc-deploy-stable:
    name: "Deploy stable documentation"
    runs-on: ubuntu-latest
    needs: [doc-build, build-library]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    steps:
      - uses: ansys/actions/doc-deploy-stable@v6
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # Uncomment doc-index-dev and doc-index stable once the repository becomes public
  # doc-index-dev:
  #   name: "Deploy dev index docs"
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   needs: doc-deploy-dev
  #   steps:
  #     - name: "Deploy the latest documentation index"
  #       uses: ansys/actions/doc-deploy-index@v6
  #       with:
  #         cname: "${{ env.DOCUMENTATION_CNAME }}/version/dev"
  #         index-name: "${{ env.LIBRARY_NAME }}-vdev"
  #         host-url: ${{ env.MEILISEARCH_HOST_URL }}
  #         api-key: ${{ env.MEILISEARCH_API_KEY }}
  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}

  # doc-index-stable:
  #   name: "Deploy stable docs index"
  #   runs-on: ubuntu-latest
  #   needs: doc-deploy-stable
  #   steps:
  #     - name: "Install Git and clone project"
  #       uses: actions/checkout@v4

  #     - name: "Install the package requirements"
  #       run: pip install -e .

  #     - name: "Get the version to PyMeilisearch"
  #       run: |
  #         VERSION=$(python -c "from src import __version__; print('.'.join(__version__.split('.')[:2]))")
  #         VERSION_MEILI=$(python -c "from src import __version__; print('-'.join(__version__.split('.')[:2]))")
  #         echo "Calculated VERSION: $VERSION"
  #         echo "Calculated VERSION_MEILI: $VERSION_MEILI"
  #         echo "VERSION=$VERSION" >> $GITHUB_ENV
  #         echo "VERSION_MEILI=$VERSION_MEILI" >> $GITHUB_ENV

  #     - name: "Deploy the latest documentation index"
  #       uses: ansys/actions/doc-deploy-index@v6
  #       with:
  #         cname: "${{ env.DOCUMENTATION_CNAME }}/version/${{ env.VERSION }}"
  #         index-name: "${{ env.LIBRARY_NAME }}-v${{ env.VERSION_MEILI }}"
  #         host-url: ${{ env.MEILISEARCH_HOST_URL }}
  #         api-key: ${{ env.MEILISEARCH_API_KEY }}
  #         python-version: ${{ env.MAIN_PYTHON_VERSION }}

  release-pypi-private:
    name: "Release to the private PyPI repository"
    runs-on: ubuntu-latest
    needs: [doc-build, build-library, update-changelog]
    steps:
      - name: "Release to the private PyPI repository"
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: ansys/actions/release-pypi-private@v6
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}

  # release-pypi-public:
  #   name: "Release to the public PyPI repository"
  #   runs-on: ubuntu-latest
  #   needs: [release-pypi-private]
  #   steps:
  #     - name: "Release to the public PyPI repository"
  #       if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
  #       uses: ansys/actions/release-pypi-public@v6
  #       with:
  #         library-name: ${{ env.DOCUMENTATION_CNAME }}
  #         twine-username: "__token__"
  #         twine-token: ${{ secrets.PYPI_TOKEN }}

  release-github:
    name: "Release to GitHub"
    runs-on: ubuntu-latest
    needs: [doc-build, release-pypi-private]
    steps:
      - name: "Release to GitHub"
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: ansys/actions/release-github@v6
        with:
          library-name: ${{ env.DOCUMENTATION_CNAME }}
