# Rendering configuration
Output basic_usage.gif
Set FontSize 20
Set Width 1920
Set Height 1080

# Generate a new project
Type "ansys-templates new pyansys-advanced"
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Sleep 1000ms
Enter
Type "clear"
Enter
Sleep 1000ms

# Show the structure of the generate project
Type "tree pyproduct-library"
Enter
Sleep 5s
